### ISSUE TITLE
Rezeptansicht - Teilfunktion

### ISSUE THREAD

**Issue by a-denzel** [alexanderreiprich/pwa-cookbook#20]
Rezepte sollen auch geteilt werden können. Dafür soll ein Sharebutton umgesetzt werden

Akzeptanzkriterien

- [x] Es gibt einen Sharebutton
- [x] Wenn man auf diesen klickt wird die URL inkl kurzem Beschreibungstext kopiert
- [x]  optional: alle Apps über die man sharen kann werden angezeigt

**Comment by alexanderreiprich** [comment]
Wurde mit #61 implementiert
