### ISSUE TITLE
Sprache festlegen

### ISSUE THREAD

**Issue by alexanderreiprich** [alexanderreiprich/pwa-cookbook#3]
Soll die Sprache der App Deutsch bleiben oder Englisch sein? Sollte man beides implementieren und in den Einstellungen tauschen können?

- Für Sprachwechsel müsste man wahrscheinlich jeden Text extern in einer .json-Datei speichern
- Package für Sprachwechsel würde benötigt werden
- Mehr Aufwand, aber auch mehr Inklusivität?
- Alternativ: Zum Schluss wenn noch Zeit vorhanden ist?

**Comment by a-denzel** [comment]
@alexanderreiprich ich würde einfach erstmal alles in Deutsch machen (also nicht den Code aber die UI) - da wir ohnehin die "Zielgruppe" sind

**Comment by alexanderreiprich** [comment]
Alles klar, machen wir so 👍
